# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tactic_3d_test.ui'
#
# Created: Tue Apr 21 16:15:30 2015
#      by: pyside-uic 0.2.15 running on PySide 1.2.2
#
# WARNING! All changes made in this file will be lost!

from PySide import QtCore, QtGui

class Ui_main_window(object):
    def setupUi(self, main_window):
        main_window.setObjectName("main_window")
        main_window.resize(471, 700)
        main_window.setMinimumSize(QtCore.QSize(0, 0))
        main_window.setMaximumSize(QtCore.QSize(620, 700))
        main_window.setStyleSheet("font: 8pt \"Arial\";")
        self.gridLayout = QtGui.QGridLayout(main_window)
        self.gridLayout.setObjectName("gridLayout")
        self.file_list_layout = QtGui.QVBoxLayout()
        self.file_list_layout.setSpacing(3)
        self.file_list_layout.setObjectName("file_list_layout")
        self.file_list_label = QtGui.QLabel(main_window)
        self.file_list_label.setAlignment(QtCore.Qt.AlignCenter)
        self.file_list_label.setObjectName("file_list_label")
        self.file_list_layout.addWidget(self.file_list_label)
        self.file_list = QtGui.QListWidget(main_window)
        self.file_list.setObjectName("file_list")
        self.file_list_layout.addWidget(self.file_list)
        self.action_menu = QtGui.QVBoxLayout()
        self.action_menu.setObjectName("action_menu")
        self.open_button = QtGui.QPushButton(main_window)
        self.open_button.setObjectName("open_button")
        self.action_menu.addWidget(self.open_button)
        self.line_6 = QtGui.QFrame(main_window)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.action_menu.addWidget(self.line_6)
        self.publish_button = QtGui.QPushButton(main_window)
        self.publish_button.setObjectName("publish_button")
        self.action_menu.addWidget(self.publish_button)
        self.file_list_layout.addLayout(self.action_menu)
        self.gridLayout.addLayout(self.file_list_layout, 4, 0, 1, 1)
        self.file_path_layout = QtGui.QVBoxLayout()
        self.file_path_layout.setSpacing(3)
        self.file_path_layout.setObjectName("file_path_layout")
        self.login_layout = QtGui.QHBoxLayout()
        self.login_layout.setObjectName("login_layout")
        self.login_label = QtGui.QLabel(main_window)
        self.login_label.setMinimumSize(QtCore.QSize(60, 0))
        self.login_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.login_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.login_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.login_label.setObjectName("login_label")
        self.login_layout.addWidget(self.login_label)
        self.login_name = QtGui.QLineEdit(main_window)
        self.login_name.setEnabled(True)
        self.login_name.setBaseSize(QtCore.QSize(0, 0))
        self.login_name.setAlignment(QtCore.Qt.AlignCenter)
        self.login_name.setReadOnly(True)
        self.login_name.setObjectName("login_name")
        self.login_layout.addWidget(self.login_name)
        self.logout_button = QtGui.QPushButton(main_window)
        self.logout_button.setMaximumSize(QtCore.QSize(21, 21))
        self.logout_button.setToolTip("")
        self.logout_button.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/sign-out_222222_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.logout_button.setIcon(icon)
        self.logout_button.setObjectName("logout_button")
        self.login_layout.addWidget(self.logout_button)
        self.file_path_layout.addLayout(self.login_layout)
        self.save_path_layout = QtGui.QHBoxLayout()
        self.save_path_layout.setObjectName("save_path_layout")
        self.save_path_label = QtGui.QLabel(main_window)
        self.save_path_label.setMinimumSize(QtCore.QSize(60, 0))
        self.save_path_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.save_path_label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.save_path_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.save_path_label.setObjectName("save_path_label")
        self.save_path_layout.addWidget(self.save_path_label)
        self.save_path = QtGui.QLineEdit(main_window)
        self.save_path.setBaseSize(QtCore.QSize(0, 0))
        self.save_path.setReadOnly(True)
        self.save_path.setObjectName("save_path")
        self.save_path_layout.addWidget(self.save_path)
        self.open_path_button = QtGui.QPushButton(main_window)
        self.open_path_button.setMaximumSize(QtCore.QSize(21, 21))
        self.open_path_button.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/folder-open-o_222222_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_path_button.setIcon(icon1)
        self.open_path_button.setObjectName("open_path_button")
        self.save_path_layout.addWidget(self.open_path_button)
        self.file_path_layout.addLayout(self.save_path_layout)
        self.save_file_layout = QtGui.QHBoxLayout()
        self.save_file_layout.setObjectName("save_file_layout")
        self.save_file_label = QtGui.QLabel(main_window)
        self.save_file_label.setMinimumSize(QtCore.QSize(60, 0))
        self.save_file_label.setMaximumSize(QtCore.QSize(60, 16777215))
        self.save_file_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.save_file_label.setObjectName("save_file_label")
        self.save_file_layout.addWidget(self.save_file_label)
        self.save_file = QtGui.QLineEdit(main_window)
        self.save_file.setReadOnly(True)
        self.save_file.setObjectName("save_file")
        self.save_file_layout.addWidget(self.save_file)
        self.save_button = QtGui.QPushButton(main_window)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.save_button.sizePolicy().hasHeightForWidth())
        self.save_button.setSizePolicy(sizePolicy)
        self.save_button.setMaximumSize(QtCore.QSize(21, 21))
        self.save_button.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/save_222222_12.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_button.setIcon(icon2)
        self.save_button.setObjectName("save_button")
        self.save_file_layout.addWidget(self.save_button)
        self.file_path_layout.addLayout(self.save_file_layout)
        self.gridLayout.addLayout(self.file_path_layout, 3, 0, 1, 1)
        self.main_selection = QtGui.QHBoxLayout()
        self.main_selection.setSpacing(1)
        self.main_selection.setObjectName("main_selection")
        self.tabProject = QtGui.QTabWidget(main_window)
        self.tabProject.setMinimumSize(QtCore.QSize(200, 0))
        self.tabProject.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabProject.setTabPosition(QtGui.QTabWidget.North)
        self.tabProject.setTabsClosable(False)
        self.tabProject.setObjectName("tabProject")
        self.project_tab = QtGui.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.project_tab.setFont(font)
        self.project_tab.setObjectName("project_tab")
        self.gridLayout_4 = QtGui.QGridLayout(self.project_tab)
        self.gridLayout_4.setSpacing(2)
        self.gridLayout_4.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.project_label = QtGui.QLabel(self.project_tab)
        self.project_label.setAlignment(QtCore.Qt.AlignCenter)
        self.project_label.setObjectName("project_label")
        self.verticalLayout_11.addWidget(self.project_label)
        self.project_list = QtGui.QListWidget(self.project_tab)
        self.project_list.setObjectName("project_list")
        self.verticalLayout_11.addWidget(self.project_list)
        self.project_info = QtGui.QTableWidget(self.project_tab)
        self.project_info.setMinimumSize(QtCore.QSize(190, 91))
        self.project_info.setMaximumSize(QtCore.QSize(16777215, 91))
        self.project_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.project_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.project_info.setAutoScroll(False)
        self.project_info.setAlternatingRowColors(True)
        self.project_info.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.project_info.setShowGrid(True)
        self.project_info.setGridStyle(QtCore.Qt.DotLine)
        self.project_info.setWordWrap(False)
        self.project_info.setCornerButtonEnabled(False)
        self.project_info.setColumnCount(1)
        self.project_info.setObjectName("project_info")
        self.project_info.setColumnCount(1)
        self.project_info.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.project_info.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        item.setFlags(QtCore.Qt.NoItemFlags)
        self.project_info.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.project_info.setItem(4, 0, item)
        self.project_info.horizontalHeader().setVisible(False)
        self.project_info.horizontalHeader().setCascadingSectionResizes(True)
        self.project_info.horizontalHeader().setDefaultSectionSize(150)
        self.project_info.horizontalHeader().setHighlightSections(True)
        self.project_info.horizontalHeader().setMinimumSectionSize(150)
        self.project_info.horizontalHeader().setStretchLastSection(True)
        self.project_info.verticalHeader().setDefaultSectionSize(18)
        self.verticalLayout_11.addWidget(self.project_info)
        self.gridLayout_4.addLayout(self.verticalLayout_11, 2, 0, 1, 1)
        self.tabProject.addTab(self.project_tab, "")
        self.main_selection.addWidget(self.tabProject)
        self.tabProductionType = QtGui.QTabWidget(main_window)
        self.tabProductionType.setMinimumSize(QtCore.QSize(250, 0))
        self.tabProductionType.setMaximumSize(QtCore.QSize(350, 16777215))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.tabProductionType.setFont(font)
        self.tabProductionType.setTabPosition(QtGui.QTabWidget.North)
        self.tabProductionType.setTabsClosable(False)
        self.tabProductionType.setObjectName("tabProductionType")
        self.assets_tab = QtGui.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.assets_tab.setFont(font)
        self.assets_tab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.assets_tab.setObjectName("assets_tab")
        self._2 = QtGui.QGridLayout(self.assets_tab)
        self._2.setSpacing(2)
        self._2.setContentsMargins(1, 1, 1, 1)
        self._2.setObjectName("_2")
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.asset_label = QtGui.QLabel(self.assets_tab)
        self.asset_label.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_label.setObjectName("asset_label")
        self.verticalLayout_2.addWidget(self.asset_label)
        self.asset_list = QtGui.QListWidget(self.assets_tab)
        self.asset_list.setObjectName("asset_list")
        self.verticalLayout_2.addWidget(self.asset_list)
        self.horizontalLayout_6.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.asset_process_lable = QtGui.QLabel(self.assets_tab)
        self.asset_process_lable.setAlignment(QtCore.Qt.AlignCenter)
        self.asset_process_lable.setObjectName("asset_process_lable")
        self.verticalLayout.addWidget(self.asset_process_lable)
        self.asset_process_list = QtGui.QListWidget(self.assets_tab)
        self.asset_process_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.asset_process_list.setObjectName("asset_process_list")
        self.verticalLayout.addWidget(self.asset_process_list)
        self.horizontalLayout_6.addLayout(self.verticalLayout)
        self.verticalLayout_6.addLayout(self.horizontalLayout_6)
        self.asset_info = QtGui.QTableWidget(self.assets_tab)
        self.asset_info.setMinimumSize(QtCore.QSize(0, 91))
        self.asset_info.setMaximumSize(QtCore.QSize(16777215, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.asset_info.setFont(font)
        self.asset_info.setStyleSheet("")
        self.asset_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.asset_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.asset_info.setAutoScroll(False)
        self.asset_info.setAlternatingRowColors(True)
        self.asset_info.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.asset_info.setShowGrid(True)
        self.asset_info.setGridStyle(QtCore.Qt.DotLine)
        self.asset_info.setWordWrap(False)
        self.asset_info.setCornerButtonEnabled(False)
        self.asset_info.setColumnCount(1)
        self.asset_info.setObjectName("asset_info")
        self.asset_info.setColumnCount(1)
        self.asset_info.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.asset_info.setItem(4, 0, item)
        self.asset_info.horizontalHeader().setVisible(False)
        self.asset_info.horizontalHeader().setCascadingSectionResizes(True)
        self.asset_info.horizontalHeader().setDefaultSectionSize(500)
        self.asset_info.horizontalHeader().setHighlightSections(True)
        self.asset_info.horizontalHeader().setMinimumSectionSize(30)
        self.asset_info.horizontalHeader().setStretchLastSection(True)
        self.asset_info.verticalHeader().setDefaultSectionSize(18)
        self.verticalLayout_6.addWidget(self.asset_info)
        self._2.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabProductionType.addTab(self.assets_tab, "")
        self.shots_tab = QtGui.QWidget()
        self.shots_tab.setEnabled(True)
        self.shots_tab.setObjectName("shots_tab")
        self.gridLayout_2 = QtGui.QGridLayout(self.shots_tab)
        self.gridLayout_2.setSpacing(2)
        self.gridLayout_2.setContentsMargins(1, 1, 1, 1)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.shot_label = QtGui.QLabel(self.shots_tab)
        self.shot_label.setAlignment(QtCore.Qt.AlignCenter)
        self.shot_label.setObjectName("shot_label")
        self.verticalLayout_10.addWidget(self.shot_label)
        self.shot_list = QtGui.QListWidget(self.shots_tab)
        self.shot_list.setObjectName("shot_list")
        self.verticalLayout_10.addWidget(self.shot_list)
        self.horizontalLayout.addLayout(self.verticalLayout_10)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.shot_process_label = QtGui.QLabel(self.shots_tab)
        self.shot_process_label.setAlignment(QtCore.Qt.AlignCenter)
        self.shot_process_label.setObjectName("shot_process_label")
        self.verticalLayout_13.addWidget(self.shot_process_label)
        self.shot_process_list = QtGui.QListWidget(self.shots_tab)
        self.shot_process_list.setMaximumSize(QtCore.QSize(150, 16777215))
        self.shot_process_list.setObjectName("shot_process_list")
        self.verticalLayout_13.addWidget(self.shot_process_list)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.shot_info = QtGui.QTableWidget(self.shots_tab)
        self.shot_info.setMinimumSize(QtCore.QSize(0, 91))
        self.shot_info.setMaximumSize(QtCore.QSize(16777215, 91))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setWeight(50)
        font.setItalic(False)
        font.setBold(False)
        self.shot_info.setFont(font)
        self.shot_info.setStyleSheet("")
        self.shot_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shot_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.shot_info.setAutoScroll(False)
        self.shot_info.setAlternatingRowColors(True)
        self.shot_info.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.shot_info.setShowGrid(True)
        self.shot_info.setGridStyle(QtCore.Qt.DotLine)
        self.shot_info.setWordWrap(False)
        self.shot_info.setCornerButtonEnabled(False)
        self.shot_info.setColumnCount(1)
        self.shot_info.setObjectName("shot_info")
        self.shot_info.setColumnCount(1)
        self.shot_info.setRowCount(5)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setVerticalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setVerticalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setVerticalHeaderItem(2, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setVerticalHeaderItem(3, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setVerticalHeaderItem(4, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setItem(0, 0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setItem(1, 0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setItem(2, 0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setItem(3, 0, item)
        item = QtGui.QTableWidgetItem()
        self.shot_info.setItem(4, 0, item)
        self.shot_info.horizontalHeader().setVisible(False)
        self.shot_info.horizontalHeader().setCascadingSectionResizes(True)
        self.shot_info.horizontalHeader().setDefaultSectionSize(500)
        self.shot_info.horizontalHeader().setHighlightSections(True)
        self.shot_info.horizontalHeader().setMinimumSectionSize(30)
        self.shot_info.horizontalHeader().setStretchLastSection(True)
        self.shot_info.verticalHeader().setDefaultSectionSize(18)
        self.verticalLayout_4.addWidget(self.shot_info)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.tabProductionType.addTab(self.shots_tab, "")
        self.main_selection.addWidget(self.tabProductionType)
        self.gridLayout.addLayout(self.main_selection, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_9 = QtGui.QPushButton(main_window)
        self.pushButton_9.setMaximumSize(QtCore.QSize(24, 24))
        self.pushButton_9.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/play_00ddff_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_9.setIcon(icon3)
        self.pushButton_9.setObjectName("pushButton_9")
        self.horizontalLayout_4.addWidget(self.pushButton_9)
        self.pushButton_10 = QtGui.QPushButton(main_window)
        self.pushButton_10.setMaximumSize(QtCore.QSize(24, 16777215))
        self.pushButton_10.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/pause_ffe11a_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_10.setIcon(icon4)
        self.pushButton_10.setObjectName("pushButton_10")
        self.horizontalLayout_4.addWidget(self.pushButton_10)
        self.pushButton_11 = QtGui.QPushButton(main_window)
        self.pushButton_11.setMaximumSize(QtCore.QSize(24, 16777215))
        self.pushButton_11.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/stop_d60000_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_11.setIcon(icon5)
        self.pushButton_11.setObjectName("pushButton_11")
        self.horizontalLayout_4.addWidget(self.pushButton_11)
        self.pushButton_12 = QtGui.QPushButton(main_window)
        self.pushButton_12.setMaximumSize(QtCore.QSize(24, 16777215))
        self.pushButton_12.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap("//art-1405260002/d/assets/scripts/maya_scripts/icons/check_00cc11_24.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_12.setIcon(icon6)
        self.pushButton_12.setObjectName("pushButton_12")
        self.horizontalLayout_4.addWidget(self.pushButton_12)
        self.line = QtGui.QFrame(main_window)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_4.addWidget(self.line)
        self.gridLayout.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(main_window)
        self.tabProject.setCurrentIndex(0)
        self.tabProductionType.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        main_window.setWindowTitle(QtGui.QApplication.translate("main_window", "TACTIC", None, QtGui.QApplication.UnicodeUTF8))
        self.file_list_label.setText(QtGui.QApplication.translate("main_window", "Files", None, QtGui.QApplication.UnicodeUTF8))
        self.open_button.setText(QtGui.QApplication.translate("main_window", "Open", None, QtGui.QApplication.UnicodeUTF8))
        self.publish_button.setText(QtGui.QApplication.translate("main_window", "Publish", None, QtGui.QApplication.UnicodeUTF8))
        self.login_label.setText(QtGui.QApplication.translate("main_window", "作者", None, QtGui.QApplication.UnicodeUTF8))
        self.save_path_label.setText(QtGui.QApplication.translate("main_window", "存檔路徑:", None, QtGui.QApplication.UnicodeUTF8))
        self.save_file_label.setText(QtGui.QApplication.translate("main_window", "存檔名:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_label.setText(QtGui.QApplication.translate("main_window", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.project_info.verticalHeaderItem(0).setText(QtGui.QApplication.translate("main_window", "專案:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_info.verticalHeaderItem(1).setText(QtGui.QApplication.translate("main_window", "案型:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_info.verticalHeaderItem(2).setText(QtGui.QApplication.translate("main_window", "窗口:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_info.verticalHeaderItem(3).setText(QtGui.QApplication.translate("main_window", "開始:", None, QtGui.QApplication.UnicodeUTF8))
        self.project_info.verticalHeaderItem(4).setText(QtGui.QApplication.translate("main_window", "結束:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.project_info.isSortingEnabled()
        self.project_info.setSortingEnabled(False)
        self.project_info.setSortingEnabled(__sortingEnabled)
        self.tabProject.setTabText(self.tabProject.indexOf(self.project_tab), QtGui.QApplication.translate("main_window", "Projects", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_label.setText(QtGui.QApplication.translate("main_window", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_process_lable.setText(QtGui.QApplication.translate("main_window", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info.verticalHeaderItem(0).setText(QtGui.QApplication.translate("main_window", "物件:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info.verticalHeaderItem(1).setText(QtGui.QApplication.translate("main_window", "類型:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info.verticalHeaderItem(2).setText(QtGui.QApplication.translate("main_window", "分配:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info.verticalHeaderItem(3).setText(QtGui.QApplication.translate("main_window", "開始:", None, QtGui.QApplication.UnicodeUTF8))
        self.asset_info.verticalHeaderItem(4).setText(QtGui.QApplication.translate("main_window", "結束:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.asset_info.isSortingEnabled()
        self.asset_info.setSortingEnabled(False)
        self.asset_info.setSortingEnabled(__sortingEnabled)
        self.tabProductionType.setTabText(self.tabProductionType.indexOf(self.assets_tab), QtGui.QApplication.translate("main_window", "Assets", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_label.setText(QtGui.QApplication.translate("main_window", "Shots", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_process_label.setText(QtGui.QApplication.translate("main_window", "Process", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info.verticalHeaderItem(0).setText(QtGui.QApplication.translate("main_window", "物件:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info.verticalHeaderItem(1).setText(QtGui.QApplication.translate("main_window", "類型:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info.verticalHeaderItem(2).setText(QtGui.QApplication.translate("main_window", "分配:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info.verticalHeaderItem(3).setText(QtGui.QApplication.translate("main_window", "開始:", None, QtGui.QApplication.UnicodeUTF8))
        self.shot_info.verticalHeaderItem(4).setText(QtGui.QApplication.translate("main_window", "結束:", None, QtGui.QApplication.UnicodeUTF8))
        __sortingEnabled = self.shot_info.isSortingEnabled()
        self.shot_info.setSortingEnabled(False)
        self.shot_info.setSortingEnabled(__sortingEnabled)
        self.tabProductionType.setTabText(self.tabProductionType.indexOf(self.shots_tab), QtGui.QApplication.translate("main_window", "Shots", None, QtGui.QApplication.UnicodeUTF8))

